stages:
  - build
  - build-prod
  - test
  - deploy
  - service
  
build:compileCommander_dev:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:latest
  script:
    - cd Birthday-Bot-Sourcecode
    - dotnet build
    - cd ..
    - mkdir result
    - cp -Rv Birthday-Bot-Sourcecode/Birthday-Bot-Sourcecode/bin/Debug/net*/* result/
  only:
    - /^dev/.*$/i
    - Development
    - main
    - master
    - master-publish
    - tags
    - bugfix-release
    - /^bugfix-rel/.*$/i
  artifacts:
    paths:
      - result/*

build:compileCommander_prod:
  stage: build-prod
  image: mcr.microsoft.com/dotnet/sdk:latest
  script:
    - cd Birthday-Bot-Sourcecode
    - dotnet build --configuration Release
    - cd ..
    - mkdir result-release
    - cp -Rv Birthday-Bot-Sourcecode/Birthday-Bot-Sourcecode/bin/Release/net*/* result-release/
    - chown -Rv 998:998 result-release
  only:
    - master
    - master-publish
    - tags
  artifacts:
    paths:
      - result-release/*.dll
      - result-release/Birthday-Bot-Sourcecode
      - result-release/config.json
  dependencies: []

sast:
  stage: test
  needs: 
    - build:compileCommander_dev
include:
- template: Jobs/SAST.gitlab-ci.yml
- template: Jobs/Secret-Detection.gitlab-ci.yml

deploy_enroleBot_dev:
  stage: deploy
  tags:
    - deployment-birthday-bot
  only:
    - master
    - master-publish
    - tags
  needs:
    - build:compileCommander_dev
    - build:compileCommander_prod
    - secret_detection
    - semgrep-sast
  dependencies:
    - build:compileCommander_prod
  script:
    - chmod +x deploy/bash/install.sh
    - sudo ./deploy/bash/install.sh
    - sudo systemctl stop bithday-bot.service
    - sudo mkdir -p /opt/birthday-bot
    - rm -Rv /opt/birthday-bot/* || true
    - cp -Rv result-release/* /opt/birthday-bot/
    - cp /etc/birthday-bot/dev.overwrite.json /opt/birthday-bot/overwrite.json
    - sudo systemctl start bithday-bot.service
  when: manual
